vich_uploader:
    db_driver: orm

    metadata:
        type: attribute

    mappings:
       eleves:
           uri_prefix: /uploads/photos
           upload_destination: '%kernel.project_dir%/public/uploads/photos'
           namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

           inject_on_load: false
           delete_on_update: true
           delete_on_remove: true
